services:

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: [ "CMD", "curl", "-k", "nginx:80" ]
      interval: 30s
      timeout: 30s
      start_period: 30s
      retries: 10
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./certbot/certs/:/etc/nginx/ssl/:rw
      - ./nginx/autoreload.sh:/docker-entrypoint.d/autoreload.sh
    depends_on:
      #  certbot:
      #    condition: service_completed_successfully
      linux_tweet_app:
        condition: service_started

  linux_tweet_app:
    build: ./linux_tweet_app
    healthcheck:
      test: [ "CMD", "curl", "linux_tweet_app:80" ]
      interval: 30s
      timeout: 30s
      start_period: 30s
      retries: 10
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - backend

  certbot_renew:
    build: ./certbot-renew
    restart: unless-stopped
    stop_grace_period: 1s
    volumes:
      - ./certbot/certs/:/etc/letsencrypt/:rw
      - ./certbot-renew/renewloop.sh:/renewloop.sh

#  certbot:
#    build: ./certbot
#    volumes:
#      - ./certbot/certs/:/etc/letsencrypt/:rw
#    ports:
#      - "80:80"

networks:
  backend:
    driver: bridge
